"""
Cell routes module for handling cell-related HTTP endpoints.
"""

# Generated by Copilot
from typing import List
from fastapi import APIRouter, HTTPException, Body
from pydantic import BaseModel
from app.db.session import SessionLocal
from app.types.image import ApiCell
from app.services.cell import cell_service

router = APIRouter()


class CellCreate(BaseModel):
    name: str
    description: str 


class CellUpdate(BaseModel):
    name: str 
    description: str 


@router.get("/", response_model=List[ApiCell])
def get_all_cells():
    """Get all cell types in the database."""
    session = SessionLocal()
    try:
        return cell_service.get_all_cells(session)
    finally:
        session.close()


@router.get("/get/{image_id}")
def get_cells() -> List[ApiCell]:
    """Compatibility method for existing code - get all cells."""
    session = SessionLocal()
    try:
        return cell_service.get_all_cells(session)
    finally:
        session.close()


@router.get("/{cell_id}", response_model=ApiCell)
def get_cell(cell_id: int):
    """Get a specific cell by ID."""
    session = SessionLocal()
    try:
        cell = cell_service.get_cell_by_id(session, cell_id)
        if cell is None:
            raise HTTPException(status_code=404, detail="Cell not found")
        return cell
    finally:
        session.close()


@router.post("/", response_model=ApiCell)
def create_cell(cell: CellCreate):
    """Create a new cell type."""
    session = SessionLocal()
    try:
        return cell_service.create_cell(session, cell.name, cell.description)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    finally:
        session.close()


@router.post("/save/{image_id}")
def add_cell(name: str):
    """Legacy method for compatibility with existing code."""
    session = SessionLocal()
    try:
        try:
            cell = cell_service.create_cell(session, name)
            return {"message": "Cell added successfully", "id": cell.id}
        except ValueError:
            # If cell already exists, return it
            existing = cell_service.get_all_cells(session)
            cell = next((c for c in existing if c.name == name), None)
            if cell:
                return {"message": "Cell already exists", "id": cell.id}
            raise  # Re-raise if not found
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        session.close()


@router.put("/{cell_id}", response_model=ApiCell)
def update_cell(cell_id: int, cell: CellUpdate):
    """Update an existing cell type."""
    session = SessionLocal()
    try:
        return cell_service.update_cell(session, cell_id, cell.name, cell.description)
    except ValueError as e:
        if "not found" in str(e):
            raise HTTPException(status_code=404, detail=str(e))
        else:
            raise HTTPException(status_code=400, detail=str(e))
    finally:
        session.close()


@router.delete("/{cell_id}")
def delete_cell(cell_id: int):
    """Delete a cell type and its associated masks."""
    session = SessionLocal()
    try:
        result = cell_service.delete_cell(session, cell_id)
        return {
            "message": "Cell deleted successfully",
            "id": result["id"],
            "masks_deleted": result["masks_deleted"],
        }
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    finally:
        session.close()
