"""
Monitoring routes module for handling system monitoring endpoints.
"""

# Generated by Copilot
from fastapi import APIRouter
from app.services.monitoring import system_metrics
from app.types.monitor import SystemMetrics, SystemResponse, DataUsageResponse

router = APIRouter()


@router.get("/system", response_model=SystemResponse)
def get_system_info() -> SystemResponse:
    """Get static system information."""
    return system_metrics.get_system_info()


@router.get("/data-usage", response_model=DataUsageResponse)
def get_data_usage() -> DataUsageResponse:
    """Get detailed information about data directory usage."""
    return system_metrics.get_data_usage()


@router.get("/metrics", response_model=SystemMetrics)
def get_system_metrics() -> SystemMetrics:
    """Get real-time system metrics (CPU, Memory, GPU)."""
    return system_metrics.get_system_metrics()
