import base64
import os

from numpy import ndarray


def ToBase64(path: str) -> str:
    """
    Convert a file to a base64 string.

    Args:
        path (str): The path to the file.

    Returns:
        str: The base64 string of the file.
    """

    with open(path, "rb") as file:
        mimetype = path.split(".")[-1]
        base = base64.b64encode(file.read()).decode("utf-8")
        return f"data:image/{mimetype};base64,{base}"
def ImageToBase64(buffer: ndarray) -> str:
    """
    Convert an image to a base64 string.

    Args:
        image (ndarray): The image array.

    Returns:
        str: The base64 string of the image.
    """
    return f"data:image/png;base64,{base64.b64encode(buffer).decode('utf-8')}"

    with open(path, "rb") as file:
        mimetype = path.split(".")[-1]
        base = base64.b64encode(file.read()).decode("utf-8")
        return f"data:image/{mimetype};base64,{base}"


def base64_to_file(data_uri: str, output_path: str):
    _, encoded = data_uri.split(",", 1)
    binary_data = base64.b64decode(encoded)

    # Generated by Copilot
    dir_name = os.path.dirname(output_path)
    if dir_name and not os.path.exists(dir_name):
        os.makedirs(dir_name, exist_ok=True)
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "wb") as f:
        f.write(binary_data)
