"""
Mask routes module for handling mask-related HTTP endpoints.
"""

# Generated by Copilot
from typing import Literal, List
from fastapi import APIRouter, Body, Query, HTTPException
from API.db.session import SessionLocal
from shared.types.image import (
    ApiMask,
    MaskUpdateResponse,
    MaskMatrix,
    MaskMatricesResponse,
    MaskSaveRequest,
)
from API.services.image import mask_service, health_service

router = APIRouter()


@router.get("/get/{image_id}", response_model=List[ApiMask])
def get_masks(image_id: int) -> List[ApiMask]:
    """
    Get all masks for a specific image.

    Args:
        image_id: ID of the image to get masks for
    """
    session = SessionLocal()
    try:
        return mask_service.get_masks(session, image_id)
    finally:
        session.close()


@router.post("/save/{image_id}")
def save_masks(image_id: int, body: List[MaskSaveRequest] = Body(...)):
    """
    Save masks for an image.

    Args:
        image_id: ID of the image to save masks for
        body: List of masks to save
    """
    session = SessionLocal()
    try:
        mask_service.save_masks(session, image_id, body)
        return {"message": "Masks saved successfully"}
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        session.rollback()
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        session.close()


@router.put("/done/{mask_id}", response_model=MaskUpdateResponse)
def mark_mask_done(
    mask_id: int, which: Literal["segmentation", "annotation"] = Query(None)
) -> MaskUpdateResponse:
    """
    Mark a mask as done.

    Args:
        mask_id: ID of the mask to mark as done
    """
    if which is None:
        raise HTTPException(status_code=400, detail="Parameter 'which' is required")

    session = SessionLocal()
    try:
        mask_service.mark_mask_done(session, mask_id, which)
        return MaskUpdateResponse(message="Mask marked as done")
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        session.rollback()
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        session.close()


@router.post("/alternate")
def alternate_masks(image_id: int, mask1: str, mask2: str):
    """
    Alternate (swap) two masks for an image.

    Args:
        image_id: ID of the image
        mask1: First mask filename
        mask2: Second mask filename
    """
    session = SessionLocal()
    try:
        mask_service.alternate_masks(session, image_id, mask1, mask2)
        return {"message": "Masks alternated successfully"}
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        session.rollback()
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        session.close()


@router.get("/matrices/{image_id}")
def get_mask_matrices(image_id: int) -> MaskMatricesResponse:
    """
    Get labeled regions matrix and health status matrices for an image.

    Args:
        image_id: ID of the image

    Returns:
        MaskMatricesResponse containing:
        - masks: List of MaskMatrix objects, each containing:
            - mask_id: ID of the mask
            - cell_id: ID of the cell type
            - labeledRegions: Matrix where each region has a unique ID
            - mask: Matrix where 0: background, 1: unhealthy, 2: healthy
    """
    session = SessionLocal()
    try:
        # Get the matrices
        matrix_tuples = health_service.get_region_matrices(image_id, session)

        # Convert matrices to response format
        masks = [
            MaskMatrix(
                mask_id=mask_id,
                cell_id=cell_id,
                labeledRegions=labeled_regions.tolist(),
                mask=mask_matrix.tolist(),
            )
            for mask_id, cell_id, labeled_regions, mask_matrix in matrix_tuples
        ]

        return MaskMatricesResponse(masks=masks)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        session.close()
